export const GET_VEHICLES = 'GET_VEHICLES'
export const SET_VEHICLES = 'SET_VEHICLES'
export const START_LOADING_VEHICLES = 'START_LOADING_VEHICLES'
export const STOP_LOADING_VEHICLES = 'STOP_LOADING_VEHICLES'

export const GET_DEALERS = 'GET_DEALERS'
export const SET_DEALERS = 'SET_DEALERS'
